/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WyCash;

import org.junit.Test;
import static org.junit.Assert.*;

public class MoneyTest {
    @Test public void testMultiplication() {
        //TODO:
    	//$5 + 10 CHF = $10 if rate is 2:1
    	//$5 * 2 = $10
    	//Make amount private
    	//Dollar side-effects?
    	//Money rounding?
    	Dollar five = new Dollar(5);
        five.times(2);
        assertEquals(10, five.amount);
    }
}
