/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wycash;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class MoneyTest {
    @Test public void testMultiplication() {
        //TODO:
    	//$5 + 10 CHF = $10 if rate is 2:1
    	//Make amount private
    	//Money rounding?
    	//
    	//DONE:
    	//$5 * 2 = $10
    	//Dollar side-effects?
    	Dollar five = new Dollar(5);
    	Dollar product = five.times(2); 
        assertEquals(10, product.amount);
        product = five.times(3);
        assertEquals(15, product.amount);
    }
}
