/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wycash;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class MoneyTest {
    //TODO:
	//$5 + $5 = $10
	//$5 + 10 CHF = $10 if rate is 2:1
	//Money rounding?
	//hashCode()
	//Equal null
	//Equal object
	//
	//DONE:
	//$5 * 2 = $10
	//5 CHF * 2 = 10 CHF
	//Dollar side-effects?
	//equals()
	//Make amount private
	//Dollar/Franc duplication
	//Compare Francs with Dollars
	//Currency?
	//Common times - further dollar/franc duplication
	
    @Test public void testMultiplication() {
    	Money five = Money.dollar(5);
        assertEquals(Money.dollar(10), five.times(2));
        assertEquals(Money.dollar(15), five.times(3));
    }
    
    @Test public void testEquality() {
    	assertTrue(Money.dollar(5).equals(Money.dollar(5)));
    	assertFalse(Money.dollar(5).equals(Money.dollar(6)));
    	assertFalse(Money.franc(5).equals(Money.dollar(5)));
    }
    
    @Test public void testCurrency() {
    	assertEquals("USD", Money.dollar(1).currency());
    	assertEquals("CHF", Money.franc(1).currency());
    }
    
    @Test public void testSimpleAddition() {
    	Money five = Money.dollar(5);
    	Expression sum = five.plus(five);
    	Bank bank = new Bank();
    	Money reduced = bank.reduce(sum, "USD");
    	assertEquals(Money.dollar(10), reduced);
    }
}
