/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wycash;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class PairTest {

	@Test
	public void testPairEquality() {
		Pair pair = new Pair("xx", "yy");
		Pair equivalentPair = new Pair("xx", "yy");
		Pair someOtherPair = new Pair("xx", "zz");
		Pair pairWithNullValues = new Pair(null, null);
		Pair nullPair = null;
		Object someOtherObject = new Object();

		assertTrue(pair.equals(pair));
		assertTrue(pair.equals(equivalentPair));
		assertFalse(pair.equals(someOtherPair));
		assertFalse(pair.equals(nullPair));
		assertFalse(pair.equals(pairWithNullValues));
		assertFalse(pair.equals(someOtherObject));
	}

	@Test
	public void testPairHash() {
		Pair completePair = new Pair("xx", "yy");
		int completePairHash = completePair.hashCode();
		assert (completePairHash != 0);
		
		Pair anotherCompletePair = new Pair("abc", "def");
		int anotherCompletePairHash = anotherCompletePair.hashCode();
		assertFalse(completePairHash == anotherCompletePairHash);

		Pair incompletePair = new Pair(null, "yy");
		assert (incompletePair.hashCode() != 0);

		Pair anotherIncompletePair = new Pair("xx", null);
		assert (anotherIncompletePair.hashCode() != 0);

		Pair nullPair = new Pair(null, null);
		assert (nullPair.hashCode() != 0);
	}

}
