/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wycash;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;

import org.junit.Test;

public class PairTest {

	@Test
	public void testPairEquality() {
		Pair pair = new Pair("xx", "yy");
		Pair equivalentPair = new Pair("xx", "yy");
		Pair someOtherPair = new Pair("xx", "zz");
		Pair pairWithNullValues = new Pair(null, null);
		Pair nullPair = null;
		Object someOtherObject = new Object();

		assertEquals(pair, pair);
		assertEquals(pair, equivalentPair);
		assertNotEquals(pair, someOtherPair);
		assertNotEquals(pair, nullPair);
		assertNotEquals(pair, pairWithNullValues);
		assertNotEquals(pair, someOtherObject);
	}

	@Test
	public void testPairHash() {
		Pair completePair = new Pair("xx", "yy");
		int completePairHash = completePair.hashCode();
		assertNotEquals(completePairHash, 0);

		Pair anotherCompletePair = new Pair("abc", "def");
		int anotherCompletePairHash = anotherCompletePair.hashCode();
		assertNotEquals(completePairHash, anotherCompletePairHash);

		Pair incompletePair = new Pair(null, "yy");
		assertNotEquals(incompletePair.hashCode(), 0);

		Pair anotherIncompletePair = new Pair("xx", null);
		assertNotEquals(anotherIncompletePair.hashCode(), 0);

		Pair nullPair = new Pair(null, null);
		assertNotEquals(nullPair.hashCode(), 0);
	}

}
